apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ibidtest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ibidtest
    spec:
      containers:
      - name: ibidtest
        image: imsdev.azurecr.io/ibid/nginx_php:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
       - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: ibidtest-svc
spec:
  selector:
    app: ibidtest
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
