apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phpapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: phpapp
    spec:
      containers:
      - name: phpapp
        image: imsdev.azurecr.io/ibid/nginx_php:latest
        ports:
        - containerPort: 8000
      imagePullSecrets:
       - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: phpapp-svc
spec:
  selector:
    app: phpapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
